# Generated by Django 3.2.7 on 2021-10-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('name', models.CharField(max_length=60)),
                ('message', models.CharField(max_length=5000)),
                ('date_sent', models.DateTimeField(auto_now=True, verbose_name='message_sent_time')),
            ],
        ),
    ]
