# Generated by Django 3.2.7 on 2022-02-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_images',
        ),
    ]
