# Generated by Django 3.2.7 on 2021-10-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_floatermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=15)),
                ('year_of_birth', models.CharField(max_length=4)),
                ('english_level', models.CharField(choices=[('1', 'Nu'), ('2', 'Da, sub 6 luni'), ('3', 'Da, peste 6 luni')], max_length=20)),
                ('experience', models.CharField(choices=[('1', 'Începător'), ('2', 'Mediu'), ('3', 'Avansat')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=5000, null=True)),
                ('date_sent', models.DateTimeField(auto_now=True, verbose_name='application_sent_time')),
            ],
        ),
    ]
