# Generated by Django 3.2.7 on 2021-11-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='facebook',
            field=models.CharField(default='N/A', max_length=5000),
        ),
        migrations.AddField(
            model_name='application',
            name='instagram',
            field=models.CharField(default='N/A', max_length=5000),
        ),
        migrations.AlterField(
            model_name='application',
            name='english_level',
            field=models.CharField(choices=[('1', 'Începător'), ('2', 'Mediu'), ('3', 'Avansat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='experience',
            field=models.CharField(choices=[('1', 'Nu'), ('2', 'Da, sub 6 luni'), ('3', 'Da, peste 6 luni')], max_length=20),
        ),
    ]
