# Generated by Django 3.2.7 on 2022-02-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_post_blog_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_images',
            field=models.ImageField(null=True, upload_to='visionStudios/static/blog_images'),
        ),
    ]
