# Generated by Django 3.2.7 on 2021-10-02 23:01

from django.db import migrations, models

from django.contrib.auth.models import User

STATUS = ((0,  "Draft"), (1, "Published"))

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title',  models.CharField(max_lenght=1048)),
                ('slug', models.SlugField(max_lenght=1048)),
                ('author', models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=STATUS, default=0)),
            ],
        ),
    ]
